// examples/kit-angular-skate-park/src/app/components/title.component.ts
import { Component, computed, inject } from '@angular/core';
import {
  Field,
  LinkField,
  ScLinkDirective,
  ScTextDirective,
  SitecoreContextService,
} from '@sitecore-content-sdk/angular';
import { SxaComponent } from './content-sdk/sxa.component';

interface GraphqlItem {
  url?: { path?: string; siteName?: string };
  field?: { jsonValue?: unknown };
}

interface TitleFields {
  data?: { datasource?: GraphqlItem; contextItem?: GraphqlItem };
}

@Component({
  selector: 'app-title',
  imports: [ScTextDirective, ScLinkDirective],
  host: {
    '[attr.class]': "('component title ' + styles().trim())",
    '[attr.id]': 'renderingId()',
  },
  template: `
    <div class="component-content">
      <div class="field-title">
        @if (isEditing()) {
        <span *scText="titleField()"></span>
        } @else {
        <a *scLink="titleLinkField()"><span *scText="titleField()"></span></a>
        }
      </div>
    </div>
  `,
})
export class TitleComponent extends SxaComponent {
  private readonly context = inject(SitecoreContextService);

  readonly fieldData = computed(() => (this.fields() as TitleFields)?.data);

  readonly datasource = computed(
    () => this.fieldData()?.datasource || this.fieldData()?.contextItem
  );

  readonly titleField = computed((): Field<string> | undefined => {
    const jsonVal = this.datasource()?.field?.jsonValue as Field<string> | undefined;
    if (jsonVal) {
      return jsonVal;
    }
    const route = this.context.page()?.layout?.sitecore?.route;
    return route?.fields?.Title as Field<string> | undefined;
  });

  readonly titleLinkField = computed((): LinkField => {
    const graphqlSource = this.datasource();
    const title = this.titleField();
    const href = graphqlSource?.url?.path;
    const rawJson = graphqlSource?.field?.jsonValue as { value?: string } | undefined;
    return {
      value: {
        href,
        title: (title?.value != null ? String(title.value) : undefined) || rawJson?.value,
      },
    };
  });

  readonly isEditing = computed(() => this.context.isEditing());
}

export default TitleComponent;

// examples/kit-nextjs-location-finder/src/components/sxa/Title.tsx
import { Link, LinkField, Text, TextField, useSitecore } from '@sitecore-content-sdk/nextjs';
import React, { type JSX } from 'react';

interface Fields {
  data: {
    datasource: {
      url: {
        path: string;
        siteName: string;
      };
      field: {
        jsonValue: {
          value: string;
          metadata?: { [key: string]: unknown };
        };
      };
    };
    contextItem: {
      url: {
        path: string;
        siteName: string;
      };
      field: {
        jsonValue: {
          value: string;
          metadata?: { [key: string]: unknown };
        };
      };
    };
  };
}

type TitleProps = {
  params: { [key: string]: string };
  fields: Fields;
};

type ComponentContentProps = {
  id: string;
  styles: string;
  children: JSX.Element;
};

const ComponentContent = (props: ComponentContentProps) => {
  const id = props.id;
  return (
    <div className={`component title ${props.styles}`} id={id ? id : undefined}>
      <div className="component-content">
        <div className="field-title">{props.children}</div>
      </div>
    </div>
  );
};

export const Default = (props: TitleProps): JSX.Element => {
  const datasource = props.fields?.data?.datasource || props.fields?.data?.contextItem;
  const { page } = useSitecore();
  const { mode } = page;
  const titleField: TextField = page.layout.sitecore.route?.fields?.pageTitle as TextField;

  const link: LinkField = {
    value: {
      href: datasource?.url?.path,
      title: titleField?.value ? String(titleField.value) : datasource?.field?.jsonValue?.value,
    },
  };
  if (!mode.isNormal) {
    link.value.querystring = `sc_site=${datasource?.url?.siteName}`;
    if (!titleField?.value) {
      titleField.value = 'Title field';
      link.value.href = '#';
    }
  }

  return (
    <ComponentContent styles={props.params.styles} id={props.params.RenderingIdentifier}>
      <>
        {mode.isEditing ? (
          <Text field={titleField} />
        ) : (
          <Link field={link}>
            <Text field={titleField} />
          </Link>
        )}
      </>
    </ComponentContent>
  );
};
