// examples/kit-angular-skate-park/src/app/components/title.component.ts
import { Component, computed, inject } from '@angular/core';
import {
  Field,
  LinkField,
  ScLinkDirective,
  ScTextDirective,
  SitecoreContextService,
} from '@sitecore-content-sdk/angular';
import { SxaComponent } from './content-sdk/sxa.component';

interface GraphqlItem {
  url?: { path?: string; siteName?: string };
  field?: { jsonValue?: unknown };
}

interface TitleFields {
  data?: { datasource?: GraphqlItem; contextItem?: GraphqlItem };
}

@Component({
  selector: 'app-title',
  imports: [ScTextDirective, ScLinkDirective],
  host: {
    '[attr.class]': "('component title ' + styles().trim())",
    '[attr.id]': 'renderingId()',
  },
  template: `
    <div class="component-content">
      <div class="field-title">
        @if (isEditing()) {
        <span *scText="titleField()"></span>
        } @else {
        <a *scLink="titleLinkField()"><span *scText="titleField()"></span></a>
        }
      </div>
    </div>
  `,
})
export class TitleComponent extends SxaComponent {
  private readonly context = inject(SitecoreContextService);

  readonly fieldData = computed(() => (this.fields() as TitleFields)?.data);

  readonly datasource = computed(
    () => this.fieldData()?.datasource || this.fieldData()?.contextItem
  );

  readonly titleField = computed((): Field<string> | undefined => {
    const jsonVal = this.datasource()?.field?.jsonValue as Field<string> | undefined;
    if (jsonVal) {
      return jsonVal;
    }
    const route = this.context.page()?.layout?.sitecore?.route;
    return route?.fields?.Title as Field<string> | undefined;
  });

  readonly titleLinkField = computed((): LinkField => {
    const graphqlSource = this.datasource();
    const title = this.titleField();
    const href = graphqlSource?.url?.path;
    const rawJson = graphqlSource?.field?.jsonValue as { value?: string } | undefined;
    return {
      value: {
        href,
        title: (title?.value != null ? String(title.value) : undefined) || rawJson?.value,
      },
    };
  });

  readonly isEditing = computed(() => this.context.isEditing());
}

export default TitleComponent;

// examples/kit-nextjs-article-starter/src/components/sxa/Title.tsx
import { Text, TextField, useSitecore } from '@sitecore-content-sdk/nextjs';
import React, { JSX } from 'react';

interface Fields {
  data: {
    datasource: {
      url: {
        path: string;
        siteName: string;
      };
      field: {
        jsonValue: {
          value: string;
          metadata?: { [key: string]: unknown };
        };
      };
    };
    contextItem: {
      url: {
        path: string;
        siteName: string;
      };
      field: {
        jsonValue: {
          value: string;
          metadata?: { [key: string]: unknown };
        };
      };
    };
  };
}

type TitleProps = {
  params: { [key: string]: string };
  fields: Fields;
};

export const Default = (props: TitleProps): JSX.Element => {
  const { page } = useSitecore();
  const titleField: TextField = page.layout.sitecore.route?.fields?.pageTitle as TextField;
  
  const isPageEditing = Boolean(page.mode.isEditing);
  const modifyTitleProps = {
    ...titleField,
    value: titleField?.value || 'Add Title',
  };

  if (!page.mode.isNormal) {
    return (
      <div
        className={`component title ${props.params.styles}`}
        id={props.params.RenderingIdentifier}
      >
        <div className="component-content">
          <Text
            tag={props.params.tag}
            field={modifyTitleProps}
            editable={isPageEditing}
            className="field-title"
          />
        </div>
      </div>
    );
  }

  return (
    <div className={`component title ${props.params.styles}`} id={props.params.RenderingIdentifier}>
      <div className="component-content">
        {page.mode.isEditing ? (
          <Text
            tag={props.params.tag}
            field={modifyTitleProps}
            editable={isPageEditing}
            className="field-title"
          />
        ) : (
          <Text tag={props.params.tag} field={titleField} className="field-title" />
        )}
      </div>
    </div>
  );
};
